### ISSUE TITLE
Import Sound Files - Change the text on the buttons to read "Link selected keyword(s) to sound"

### ISSUE THREAD

**Issue by jeffwirth** [zusias/Ambient-Sound-Engine#3]

**Comment by kcappieg** [comment]
Working on this issue 1/16/16

**Comment by kcappieg** [comment]
Resizing window to be wide but short pushes the text in these buttons to overlap. Need to fix the spacing in that window size.

**Comment by jeffwirth** [comment]
Looks like the resizing issue has been resolved. Nice.
